// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi7Q96qqGL0JcUmyhyjPLJgqOjGceCB0o',
    appId: '1:934585948649:web:362d3137de3ec72ef05378',
    messagingSenderId: '934585948649',
    projectId: 'omni-health-32e46',
    authDomain: 'omni-health-32e46.firebaseapp.com',
    storageBucket: 'omni-health-32e46.appspot.com',
    measurementId: 'G-VV5MV4ZD9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaXJfnwLjA9DZ5qNPrCH_vyJW7eEwvHi4',
    appId: '1:934585948649:android:ab2dc37dcbc8c0e1f05378',
    messagingSenderId: '934585948649',
    projectId: 'omni-health-32e46',
    storageBucket: 'omni-health-32e46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdU_4YpXYQjHALlZX9uYRKlTPX5LImipY',
    appId: '1:934585948649:ios:b38693d5a0ef65e6f05378',
    messagingSenderId: '934585948649',
    projectId: 'omni-health-32e46',
    storageBucket: 'omni-health-32e46.appspot.com',
    iosClientId: '934585948649-hbn7t874t08gr8i5e63njg7qv3a3mh58.apps.googleusercontent.com',
    iosBundleId: 'com.example.omnihealth',
  );
}
